### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by nemrx** [LuisLuii/FastAPIQuickCRUD#3]
Environment: Windows 10 + Python 3.10.1 (x64) (Issue also with 3.7)

Facing the following error while trying to install via pip:

```
pip install fastapi_quickcrud==0.0.2
Collecting fastapi_quickcrud==0.0.2
  Using cached fastapi_quickcrud-0.0.2.tar.gz (37 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\rob-work\pycharmprojects\xconnect.agent\venv310\scripts\python.exe' 'c:\users\rob-work\pycharmprojects\xconnect.agent\venv310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Rob-Work\A
ppData\Local\Temp\tmp9kjdrdoz'
       cwd: C:\Users\Rob-Work\AppData\Local\Temp\pip-install-v4nip7h_\fastapi-quickcrud_9c5e5ca136504d1185d5c4dd9e880cca
  Complete output (16 lines):
  Traceback (most recent call last):
    File "c:\users\rob-work\pycharmprojects\xconnect.agent\venv310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "c:\users\rob-work\pycharmprojects\xconnect.agent\venv310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\rob-work\pycharmprojects\xconnect.agent\venv310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "C:\Users\Rob-Work\AppData\Local\Temp\pip-build-env-4fol05yn\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 44, in prepare_metadata_for_build_wheel
      builder = WheelBuilder(poetry)
    File "C:\Users\Rob-Work\AppData\Local\Temp\pip-build-env-4fol05yn\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 57, in __init__
      super(WheelBuilder, self).__init__(poetry, executable=executable)
    File "C:\Users\Rob-Work\AppData\Local\Temp\pip-build-env-4fol05yn\overlay\Lib\site-packages\poetry\core\masonry\builders\builder.py", line 85, in __init__
      self._module = Module(
    File "C:\Users\Rob-Work\AppData\Local\Temp\pip-build-env-4fol05yn\overlay\Lib\site-packages\poetry\core\masonry\utils\module.py", line 63, in __init__
      raise ModuleOrPackageNotFound(
  poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package fastapiquickcrud
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/47/a3/8af39857ce62afcb563fd700be27954ad9d28f6ae19f3e8570182edbf604/fastapi_quickcrud-0.0.2.tar.gz#sha256=e72fd906359072e48a67745e9c4be19b4f1ce92a43d0d3b5c2d2685077b3e5a5 (from https://pypi.org/simple/fasta
pi-quickcrud/) (requires-python:>=3.7). Command errored out with exit status 1: 'c:\users\rob-work\pycharmprojects\xconnect.agent\venv310\scripts\python.exe' 'c:\users\rob-work\pycharmprojects\xconnect.agent\venv310\lib\site-packages\pip\_vendor\pep517\in_process\_
in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Rob-Work\AppData\Local\Temp\tmp9kjdrdoz' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement fastapi_quickcrud==0.0.2 (from versions: 0.0.1a1, 0.0.1a2, 0.0.1a3, 0.0.1a4, 0.0.1a5, 0.0.1a6, 0.0.1a7, 0.0.1a8, 0.0.1a9, 0.0.1a10, 0.0.1a11, 0.0.1a12, 0.0.1a13, 0.0.1a14, 0.0.1a15, 0.0.1a16, 0.0.1a17, 
0.0.1a18, 0.0.1a19, 0.0.1, 0.0.2)
ERROR: No matching distribution found for fastapi_quickcrud==0.0.2
```

**Comment by LuisLuii** [comment]
Hi nemrx, thank you so much for your comment, I was uploaded the newly version to fix this problem. Let me know if there is any question

**Comment by nemrx** [comment]
Works now, thanks!
